services:
  # todo: docker run
  postgres1:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cloud
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - java

  postgres2:
    build: ./docker/postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cloud
    ports:
      - "5433:5432"
    networks:
      - java

  java:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres,mock
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres1:5432/cloud
    networks:
      - java

volumes:
  postgres_data:

networks:
  java: