app:
  hello:
    greeting: Ahoj
  current-account:
    transaction:
      get-latest-current-account-transactions-max-record-count: 20

spring:
  datasource:
    url: jdbc:h2:mem:fmfi
  jpa:
    defer-datasource-initialization: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    java:
      enabled: true
